window.JUNK_IMAGE_PATHS = [
  "junk/3D Series Star - Black Really-Thin Star.png",
  "junk/3D Series Star - Blue 7-Pointed Star.png",
  "junk/3D Series Star - Bronze 4-Pointed Star.png",
  "junk/3D Series Star - Gold Sharp Star.png",
  "junk/3D Series Star - Green Fat Star.png",
  "junk/3D Series Star - Orange Thin-Blossum Star.png",
  "junk/3D Series Star - Purple Blossum Star.png",
  "junk/3D Series Star - Red Exact Star.png",
  "junk/3D Series Star - Silver Tutorial-Sharp Star.png",
  "junk/3D Series Star - Turquoise Fat-Round Star.png",
  "junk/3D Series Star - Yellow Tutorial Star.png",
  "junk/Abstract Rainbow.png",
  "junk/Amber.png",
  "junk/Amethyst.png",
  "junk/Amulet.png",
  "junk/Angry.png",
  "junk/Ankh Blue.png",
  "junk/Ankh Brushed Gold.png",
  "junk/Ankh Brushed Silver.png",
  "junk/Ankh Gold.png",
  "junk/Ankh Green.png",
  "junk/Ankh Purple.png",
  "junk/Ankh Red.png",
  "junk/Ankh Silver.png",
  "junk/Archyesie.png",
  "junk/BG Heart2-L.png",
  "junk/Black Hand.png",
  "junk/Blue Hand.png",
  "junk/Blushing - Shy.png",
  "junk/Bracelet.png",
  "junk/Bravera.png",
  "junk/Bronze Sphere.png",
  "junk/Bullet Points - Black.png",
  "junk/Bullet Points - Blue.png",
  "junk/Bullet Points - Brown.png",
  "junk/Bullet Points - Grass Green.png",
  "junk/Bullet Points - Gray.png",
  "junk/Bullet Points - Green.png",
  "junk/Bullet Points - Indigo.png",
  "junk/Bullet Points - Maroon.png",
  "junk/Bullet Points - Orange Sun.png",
  "junk/Bullet Points - Orange.png",
  "junk/Bullet Points - Pink.png",
  "junk/Bullet Points - Purple.png",
  "junk/Bullet Points - Red.png",
  "junk/Bullet Points - Sand.png",
  "junk/Bullet Points - Teal.png",
  "junk/Bullet Points - Turquoise.png",
  "junk/Bullet Points - Violet.png",
  "junk/Bullet Points - White.png",
  "junk/Bullet Points - Winter Sky.png",
  "junk/Bullet Points - Yellow.png",
  "junk/Canary.png",
  "junk/Circlet.png",
  "junk/Claw2.png",
  "junk/Claw3.png",
  "junk/Claw4.png",
  "junk/Claw5.png",
  "junk/Claw6.png",
  "junk/Claw7.png",
  "junk/Claw8.png",
  "junk/Claw9.png",
  "junk/Command.png",
  "junk/Confused - Puzzled.png",
  "junk/Cross Blue.png",
  "junk/Cross Gold.png",
  "junk/Cross Green.png",
  "junk/Cross Purple.png",
  "junk/Cross Red.png",
  "junk/Cross Silver.png",
  "junk/Crossing Swords.png",
  "junk/Cry.png",
  "junk/D1-BL.png",
  "junk/D1-BLK.png",
  "junk/D1-GOLD.png",
  "junk/D1-GREY.png",
  "junk/D1-GRN.png",
  "junk/D1-O.png",
  "junk/D1-P.png",
  "junk/D1-PP.png",
  "junk/D1-R.png",
  "junk/D1-S.png",
  "junk/D1-Y.png",
  "junk/D2-BL.png",
  "junk/D2-BLK.png",
  "junk/D2-GOLD.png",
  "junk/D2-GREY.png",
  "junk/D2-GRN.png",
  "junk/D2-O.png",
  "junk/D2-P.png",
  "junk/D2-PP.png",
  "junk/D2-R.png",
  "junk/D2-S.png",
  "junk/D2-Y.png",
  "junk/D3-BL.png",
  "junk/D3-BLK.png",
  "junk/D3-GOLD.png",
  "junk/D3-GREY.png",
  "junk/D3-GRN.png",
  "junk/D3-O.png",
  "junk/D3-P.png",
  "junk/D3-PP.png",
  "junk/D3-R.png",
  "junk/D3-S.png",
  "junk/D3-Y.png",
  "junk/Disco Ball.png",
  "junk/Earrings.png",
  "junk/Emerald.png",
  "junk/Fern.png",
  "junk/Flower.png",
  "junk/Flowers.png",
  "junk/Frotelie.png",
  "junk/GM-Flower--Aqua.png",
  "junk/GM-Flower--Blue.png",
  "junk/GM-Flower--Green.png",
  "junk/GM-Flower--Orange.png",
  "junk/GM-Flower--Pink.png",
  "junk/GM-Flower--Purple.png",
  "junk/GM-Flower--Rose.png",
  "junk/GM-Flower--Teal.png",
  "junk/GM-Flower--Yellow.png",
  "junk/Gazing Ball.png",
  "junk/Gold Button Coin.png",
  "junk/Gold Coin.png",
  "junk/Gold Stainless Steel.png",
  "junk/Golden Coin.png",
  "junk/Golden Euclidean Coin.png",
  "junk/Grape Basket!.png",
  "junk/Grapes!.png",
  "junk/Green Frog.png",
  "junk/Green Gummy.png",
  "junk/Green Hand.png",
  "junk/Holy Cross Blue.png",
  "junk/Holy Cross Gold.png",
  "junk/Holy Cross Green.png",
  "junk/Holy Cross Purple.png",
  "junk/Holy Cross Red.png",
  "junk/Holy Cross Silver.png",
  "junk/Inflatable Shiny Mirror.png",
  "junk/JB 1.png",
  "junk/JB 10.png",
  "junk/JB 11.png",
  "junk/JB 12.png",
  "junk/JB 13.png",
  "junk/JB 14.png",
  "junk/JB 15.png",
  "junk/JB 16.png",
  "junk/JB 17.png",
  "junk/JB 18.png",
  "junk/JB 19.png",
  "junk/JB 2.png",
  "junk/JB 20.png",
  "junk/JB 3.png",
  "junk/JB 4.png",
  "junk/JB 5.png",
  "junk/JB 6.png",
  "junk/JB 7.png",
  "junk/JB 8.png",
  "junk/JB 9.png",
  "junk/Malyvera.png",
  "junk/Mirror Ball.png",
  "junk/Neckband.png",
  "junk/Necklace.png",
  "junk/OG Flower-L.png",
  "junk/OK Rose Cursor.png",
  "junk/Onyx.png",
  "junk/Orange Hand.png",
  "junk/Orange!.png",
  "junk/Orbs of Element.png",
  "junk/Ornate Cross Blue.png",
  "junk/Ornate Cross Gold.png",
  "junk/Ornate Cross Green.png",
  "junk/Ornate Cross Purple.png",
  "junk/Ornate Cross Red.png",
  "junk/Ornate Cross Silver.png",
  "junk/PG Flower.png",
  "junk/Palentie.png",
  "junk/Parthyniesa.png",
  "junk/Pink Hand.png",
  "junk/Popsickle.png",
  "junk/Purple Hand.png",
  "junk/RG Heart.png",
  "junk/RW-Designer Icon Logo: 3D Model.png",
  "junk/RW-Designer: Cursor Editor.png",
  "junk/RW-Designer: Custom.png",
  "junk/Rainbow 2.png",
  "junk/Rainbow Hands.png",
  "junk/Rainbow Mirror.png",
  "junk/Rainbow Orbs.png",
  "junk/Rainbow.png",
  "junk/Random Diamonds - DIAMOND1.png",
  "junk/Random Diamonds - DIAMOND2.png",
  "junk/Random Diamonds - DIAMOND3.png",
  "junk/Random Diamonds - DIAMOND4.png",
  "junk/Random Diamonds - DIAMOND5.png",
  "junk/Random Diamonds - DIAMOND6.png",
  "junk/Ranger Dedication.png",
  "junk/Red Hand.png",
  "junk/Reflection.png",
  "junk/Retreating Rainbow Orbs.png",
  "junk/Ring.png",
  "junk/Rose Mouse Cursor(s).png",
  "junk/Rosieta.png",
  "junk/Ruby.png",
  "junk/Sapphire.png",
  "junk/Saw1.png",
  "junk/Saw2.png",
  "junk/Saw3.png",
  "junk/Saw4.png",
  "junk/Saw5.png",
  "junk/Saw6.png",
  "junk/Saw7.png",
  "junk/Saw8.png",
  "junk/Saw9.png",
  "junk/Sleeping.png",
  "junk/Sleepy-head.png",
  "junk/Smile.png",
  "junk/Snowelianta.png",
  "junk/Spikey Black.png",
  "junk/Spikey Blue.png",
  "junk/Spikey Brown.png",
  "junk/Spikey Gold.png",
  "junk/Spikey Gray.png",
  "junk/Spikey Green.png",
  "junk/Spikey Orange.png",
  "junk/Spikey Pink.png",
  "junk/Spikey Purple.png",
  "junk/Spikey Red.png",
  "junk/Spikey Silver.png",
  "junk/Spikey Violet.png",
  "junk/Spikey Yellow.png",
  "junk/Spikey1.png",
  "junk/Spikey2.png",
  "junk/Spikey3.png",
  "junk/Spikey4.png",
  "junk/Spikey5.png",
  "junk/Spikey6.png",
  "junk/Spikey7.png",
  "junk/Spikey8.png",
  "junk/Spikey9.png",
  "junk/StarShine-BlueGreen-.png",
  "junk/StarShine-BlueGreen.png",
  "junk/StarShine-BlueOrange-.png",
  "junk/StarShine-BlueOrange.png",
  "junk/StarShine-BluePink-.png",
  "junk/StarShine-BluePink.png",
  "junk/StarShine-BluePurple-.png",
  "junk/StarShine-BluePurple.png",
  "junk/StarShine-BlueWhite-.png",
  "junk/StarShine-BlueWhite.png",
  "junk/StarShine-BlueYellow-.png",
  "junk/StarShine-BlueYellow.png",
  "junk/StarShine-GreenBlue-.png",
  "junk/StarShine-GreenBlue.png",
  "junk/StarShine-WhitePurple-.png",
  "junk/StarShine-WhitePurple.png",
  "junk/StarShine-WhiteYellow-.png",
  "junk/StarShine-WhiteYellow.png",
  "junk/StarShine-Yellow.png",
  "junk/StarShine-YellowGreen-.png",
  "junk/StarShine-YellowGreen.png",
  "junk/StarShine-YellowOrange-.png",
  "junk/StarShine-YellowOrange.png",
  "junk/StarShine-YellowWhite-.png",
  "junk/StarShine-YellowWhite.png",
  "junk/Sunnierie.png",
  "junk/Talkative - Chatty.png",
  "junk/Tapered Cross-Blue.png",
  "junk/Tapered Cross-Gold.png",
  "junk/Tapered Cross-Green.png",
  "junk/Tapered Cross-Purple.png",
  "junk/Tapered Cross-Red.png",
  "junk/Tapered Cross-Silver.png",
  "junk/Topaz.png",
  "junk/Tribal - 1.png",
  "junk/Tribal - 10.png",
  "junk/Tribal - 11.png",
  "junk/Tribal - 12.png",
  "junk/Tribal - 13.png",
  "junk/Tribal - 14.png",
  "junk/Tribal - 15.png",
  "junk/Tribal - 16.png",
  "junk/Tribal - 17.png",
  "junk/Tribal - 18.png",
  "junk/Tribal - 19.png",
  "junk/Tribal - 2.png",
  "junk/Tribal - 20.png",
  "junk/Tribal - 21.png",
  "junk/Tribal - 22.png",
  "junk/Tribal - 23.png",
  "junk/Tribal - 24.png",
  "junk/Tribal - 3.png",
  "junk/Tribal - 4.png",
  "junk/Tribal - 5.png",
  "junk/Tribal - 6.png",
  "junk/Tribal - 7.png",
  "junk/Tribal - 8.png",
  "junk/Tribal - 9.png",
  "junk/Triple Cross Blue.png",
  "junk/Triple Cross Gold.png",
  "junk/Triple Cross Green.png",
  "junk/Triple Cross Purple.png",
  "junk/Triple Cross Red.png",
  "junk/Triple Cross Silver.png",
  "junk/Tulipacea.png",
  "junk/Turquoise.png",
  "junk/US Bills - 1$.png",
  "junk/US Bills - 10$.png",
  "junk/US Bills - 100$.png",
  "junk/US Bills - 2$.png",
  "junk/US Bills - 20$.png",
  "junk/US Bills - 5$.png",
  "junk/US Bills - 50$.png",
  "junk/WG Flower-L.png",
  "junk/Watching.png",
  "junk/White Hand.png",
  "junk/YIWOYI Mirror.png",
  "junk/Yellow Gummy.png",
  "junk/Yellow Hand.png",
  "junk/Zelda Cartoon Sword.png",
  "junk/Zelda Knife.png",
  "junk/Zelda Sword Protection.png",
  "junk/Zelda Sword.png",
  "junk/Zhandoub Steel Gaze.png",
  "junk/beads1.png",
  "junk/beads2.png",
  "junk/beads3.png",
  "junk/beads4.png",
  "junk/beads5.png",
  "junk/beads6.png",
  "junk/beads7.png",
  "junk/beads8.png",
  "junk/beads9.png",
  "junk/bear_TaY_icon.png",
  "junk/bow3_dJQ_icon.png",
  "junk/bunny.png",
  "junk/bunny4_RY8_icon.png",
  "junk/cane.png",
  "junk/comfits.png",
  "junk/cottencandy_92K_icon.png",
  "junk/dropstars_65D_icon.png",
  "junk/fishpng_q7J_icon.png",
  "junk/flower (1).png",
  "junk/flower (10).png",
  "junk/flower (11).png",
  "junk/flower (12).png",
  "junk/flower (13).png",
  "junk/flower (14).png",
  "junk/flower (15).png",
  "junk/flower (16).png",
  "junk/flower (17).png",
  "junk/flower (18).png",
  "junk/flower (19).png",
  "junk/flower (2).png",
  "junk/flower (20).png",
  "junk/flower (21).png",
  "junk/flower (22).png",
  "junk/flower (23).png",
  "junk/flower (24).png",
  "junk/flower (25).png",
  "junk/flower (3).png",
  "junk/flower (4).png",
  "junk/flower (5).png",
  "junk/flower (6).png",
  "junk/flower (7).png",
  "junk/flower (8).png",
  "junk/flower (9).png",
  "junk/gem 11402_ametrine_rough_hero.png",
  "junk/gem 119007-Ency.png",
  "junk/gem 145492.png",
  "junk/gem 145498.png",
  "junk/gem 145499-Ency.png",
  "junk/gem 146111.png",
  "junk/gem 150226_lapisLazuli_rough_hero.png",
  "junk/gem 151543_iolite_rough_hero_v2.png",
  "junk/gem 151544_citrine_rough_hero.png",
  "junk/gem 153283_sunStoneRoughHero_02.png",
  "junk/gem 50756-Ency.png",
  "junk/gem 51095.png",
  "junk/gem 51115-Ency.png",
  "junk/gem 51129.png",
  "junk/gem 70094.png",
  "junk/gem 70161.png",
  "junk/gem 80172-Ency.png",
  "junk/gem 85065_roseQuartz_rough_hero.png",
  "junk/gem 86977-Ency.png",
  "junk/gem 88719.png",
  "junk/gem 88722-Ency.png",
  "junk/gem 88741-Ency.png",
  "junk/gem 95783-Ency.png",
  "junk/gem 95787-Ency.png",
  "junk/gem 97442_kunzite_rough_hero.png",
  "junk/gem 99140-Ency.png",
  "junk/gem Garnet-Rough-119007.png",
  "junk/gem amethyst.png",
  "junk/gem garnet-polished-gem.png",
  "junk/gem morganite_rough_hero.png",
  "junk/gem polished-alexandrite-gem.png",
  "junk/gem polished-amber-gems.png",
  "junk/gem polished-ametrine-gem.png",
  "junk/gem polished-aquamarine-gem.png",
  "junk/gem polished-citrine-gem.png",
  "junk/gem polished-diamond.png",
  "junk/gem polished-emerald-gem.png",
  "junk/gem polished-fancy-color-diamond.png",
  "junk/gem polished-iolite-gem.png",
  "junk/gem polished-kunzite-gem.png",
  "junk/gem polished-lapis-lazuli.png",
  "junk/gem polished-moonstone.png",
  "junk/gem polished-morganite.png",
  "junk/gem polished-opal.png",
  "junk/gem polished-peridot.png",
  "junk/gem polished-perl.png",
  "junk/gem polished-rose-quartz.png",
  "junk/gem polished-ruby.png",
  "junk/gem polished-sapphire.png",
  "junk/gem polished-spinel.png",
  "junk/gem polished-sunstone.png",
  "junk/gem polished-topaz.png",
  "junk/gem polished-tourmaline.png",
  "junk/gost_RHU_icon.png",
  "junk/hosre2_vW1_icon.png",
  "junk/hourse3_UTK_icon.png",
  "junk/icecream.png",
  "junk/kitty.png",
  "junk/kitty6_vQg_icon.png",
  "junk/lollipop.png",
  "junk/lollipops.png",
  "junk/love_4gz_icon.png",
  "junk/pegusus_BJR_icon.png",
  "junk/rainbow_aYZ_icon.png",
  "junk/remove_bg_copy_bRL_icon.png",
  "junk/rrose_dEk_icon.png",
  "junk/snowflake1.png",
  "junk/snowflake10.png",
  "junk/snowflake11.png",
  "junk/snowflake12.png",
  "junk/snowflake2.png",
  "junk/snowflake3.png",
  "junk/snowflake4.png",
  "junk/snowflake5.png",
  "junk/snowflake6.png",
  "junk/snowflake7.png",
  "junk/snowflake8.png",
  "junk/snowflake9.png",
  "junk/unicorn.png",
  "junk/whakle_o2E_icon.png"
];
